pipeline:
  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-cross-storage
    group: publishing
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  publish-production:
    image: plugins/docker
    repo: nossas/bonde-cross-storage
    group: publishing
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag
